#################
### AUTOSTART ###
#################

exec-once = systemctl --user start hyprpolkitagent
exec-once = swaync
exec-once = qs -c bar
exec-once = awww-daemon
exec-once = sleep 1 && ~/.config/hypr/scripts/wallpaper-rotation.sh
exec-once = hypridle
exec-once = qs -c overview
exec-once = swayosd-server
exec-once = steam -silent
